const test=require('node:test'),assert=require('node:assert/strict');
const {create,flush,identity,status,success}=require('./harness.cjs');
for(const opt of [{initFail:true},{outside:true},{loggedOut:true},{noToken:true}])test('initial guard '+JSON.stringify(opt),async()=>{const h=create(opt);await flush();h.phrase();await h.click('precheck');await h.click('recover');await h.click('statusCheck');assert.equal(h.calls.length,0);h.safe();});
const identities=[null,[],{}, {...identity,success:false},...['UNREGISTERED','SUSPENDED','LEAVE','TERMINATED','APPLICATION_PENDING'].map(state=>({...identity,state})),...['EMPLOYEE','SITE_MANAGER','UNKNOWN','admin'].map(permission=>({...identity,employee:{employeeId:'EMP001',permission}})),{...identity,employee:{employeeId:'EMP002',permission:'ADMIN'}}];
for(const [i,body] of identities.entries())test('identity denial '+i,async()=>{const h=create({reply:()=>({body})});await flush();await h.click('precheck');h.phrase();await h.click('recover');assert.equal(h.writes().length,0);assert.notEqual(h.state(),'READY');h.safe();});
const badStatuses=[{...status,requestStatus:'NOT_OBSERVED',currentConsistency:'UNKNOWN'},{...status,requestStatus:'UNKNOWN',historicalCompletion:null,currentConsistency:'UNKNOWN'},
 ...['ABSENT','PARTIAL','CONFLICT'].map(currentConsistency=>({...status,currentConsistency})),{...status,requestStatus:'RECOVERY_REQUIRED',historicalCompletion:null,currentConsistency:'CONFLICT'},
 {...status,requestStatus:'COMPLETED',historicalCompletion:true},...['employeeId','requestId','action'].map(k=>({...status,[k]:'WRONG'})),...['historicalCompletion','recoveryAllowed','newRequestAllowed'].map(k=>({...status,[k]:true})),
 {...status,extra:'PRIVATE_AUDIT'},...Object.keys(status).map(k=>{const b={...status};delete b[k];return b;}),{...status,historicalCompletion:0},{...status,recoveryAllowed:'false'}];
for(const [i,body]of badStatuses.entries())test('only STARTED false MATCHED precheck '+i,async()=>{const h=create({reply:({data})=>data.action.endsWith('RequestStatus')?{body}:{}});await flush();await h.click('precheck');h.phrase();await h.click('recover');assert.notEqual(h.state(),'READY');assert.equal(h.writes().length,0);h.safe();});
for(const version of ['',null,'t3-4-gas-read-diag','t4-safety-1','PRIVATE_VERSION'])test('wrong worker version '+version,async()=>{const h=create({reply:()=>({version})});await flush();await h.click('precheck');h.phrase();await h.click('recover');assert.equal(h.writes().length,0);assert.equal(h.el('error').textContent,'TRANSPORT_VERSION_REQUIRED');h.safe();});
for(const permission of ['OWNER','ADMIN'])test('valid '+permission+' and exact fresh payload',async()=>{
 const h=create({reply:({data})=>data.action==='identityBootstrap'?{body:{...identity,employee:{employeeId:'EMP001',permission},sub:'PRIVATE_SUB'}}:{body:data.action.endsWith('RequestStatus')?{...status,_gasReadDiagnostics:{unused:'PRIVATE_META'}}:success}});
 await h.ready();h.el('requestId').textContent='ALTERED';h.el('snapshot').textContent='ALTERED';h.el('reason').textContent='ALTERED';
 await h.click('recover');assert.equal(h.state(),'SUCCESS');assert.deepEqual(h.calls.map(c=>c.data.action),['identityBootstrap','employeeLifecycleBaselineRequestStatus','identityBootstrap','employeeLifecycleBaselineRequestStatus','employeeLifecycleBaselineMigrate']);assert.equal(h.writes().length,1);await h.locked();
});
for(const phrase of ['MIGRATE EMP001','RECOVER EMP001 ',' RECOVER EMP001','recover EMP001','RECOVER  EMP001','RECOVER EMP001\n',''])test('phrase exact '+JSON.stringify(phrase),async()=>{const h=create();await h.ready();h.phrase(phrase);assert(h.el('recover').disabled);await h.click('recover');assert.equal(h.writes().length,0);h.safe();});
for(const hook of ['token','fetch'])test('synchronous latch before '+hook+' reentry',async()=>{
 let count=0;const reenter=({state,stage,click,el})=>{if(['REVALIDATING','SUBMITTING'].includes(state||stage)){count++;el('recover').disabled=false;click('recover');click('precheck');click('statusCheck');}};
 const h=create(hook==='token'?{onToken:reenter}:{onFetch:reenter});await h.ready();await h.click('recover');assert.equal(h.writes().length,1);assert.equal(h.calls.length,5);assert(count>=3);await h.locked();
});
for(const [i,body]of identities.entries())test('fresh identity denies and consumes attempt '+i,async()=>{const h=create({reply:({stage,data})=>stage==='REVALIDATING'&&data.action==='identityBootstrap'?{body}:{}});await h.ready();await h.click('recover');assert.equal(h.state(),'WRITE_RESULT_UNKNOWN');assert.equal(h.writes().length,0);await h.locked();});
for(const [i,body]of badStatuses.entries())test('fresh status denies and consumes attempt '+i,async()=>{const h=create({reply:({stage,data})=>stage==='REVALIDATING'&&data.action.endsWith('RequestStatus')?{body}:{}});await h.ready();await h.click('recover');assert.equal(h.state(),'WRITE_RESULT_UNKNOWN');assert.equal(h.writes().length,0);await h.locked();});
for(const stage of ['REVALIDATING','SUBMITTING'])for(const bodyPending of [false,true])test(stage+' headers/body timeout freezes late result '+bodyPending,async()=>{
 const h=create({reply:({stage:s,data})=>s===stage&&(stage==='SUBMITTING'||data.action.endsWith('RequestStatus'))?{[bodyPending?'bodyPending':'pending']:true}:{}});await h.ready();const p=h.click('recover');await flush();h.expire();await p;assert.equal(h.state(),'WRITE_RESULT_UNKNOWN');assert.equal(h.writes().length,stage==='SUBMITTING'?1:0);h.release();await flush();assert.equal(h.state(),'WRITE_RESULT_UNKNOWN');await h.locked();
});
for(const changed of ['outside','loggedOut','noToken'])test('fresh token environment fails closed '+changed,async()=>{const opt={};const h=create(opt);await h.ready();if(changed==='outside')h.inside(false);if(changed==='loggedOut')h.logged(false);if(changed==='noToken')opt.noToken=true;await h.click('recover');assert.equal(h.writes().length,0);await h.locked();});
const successBad=[null,[],{}, {...success,extra:'PRIVATE_RAW'},...Object.keys(success).map(k=>{const b={...success};delete b[k];return b;}),...Object.entries({success:false,employeeId:'EMP002',requestId:'wrong',baselineState:'ALREADY_BASELINED',version:'1',recoveryStatus:'STARTED'}).map(([k,v])=>({...success,[k]:v})),...['0',0,2,null,true].map(version=>({...success,version}))];
const writeErrors=[{network:true},{nonJson:true},...['PATH_DENIED','CONTROLLED_MIGRATION_DENIED','RECOVERY_APPROVAL_REQUIRED','UPSTREAM_TIMEOUT','PRIVATE_EXCEPTION'].map(code=>({body:{success:false,code,message:'PRIVATE_RAW',stack:'PRIVATE_STACK'},http:400})),...successBad.map(body=>({body}))];
for(const [i,reply]of writeErrors.entries())test('terminal write outcome '+i,async()=>{const h=create({reply:({stage})=>stage==='SUBMITTING'?reply:{}});await h.ready();await h.click('recover');assert.equal(h.state(),'WRITE_RESULT_UNKNOWN');assert.equal(h.writes().length,1);await h.locked();});
const statusCases=[['COMPLETED',true,'MATCHED','STATUS_COMPLETED'],['STARTED',false,'MATCHED','STATUS_STARTED'],['RECOVERY_REQUIRED',null,'CONFLICT','STATUS_RECOVERY_REQUIRED'],['RECOVERY_REQUIRED',false,'CONFLICT','STATUS_RECOVERY_REQUIRED'],['RECOVERY_REQUIRED',true,'CONFLICT','STATUS_RECOVERY_REQUIRED'],['NOT_OBSERVED',false,'UNKNOWN','WRITE_RESULT_UNKNOWN'],['UNKNOWN',null,'UNKNOWN','WRITE_RESULT_UNKNOWN'],['STARTED',false,'PARTIAL','WRITE_RESULT_UNKNOWN'],['STARTED',false,'ABSENT','WRITE_RESULT_UNKNOWN']];
for(const [requestStatus,historicalCompletion,currentConsistency,next]of statusCases)test('post attempt status '+requestStatus+'/'+currentConsistency,async()=>{const h=create({reply:({stage})=>stage==='STATUS_CHECKING'?{body:{...status,requestStatus,historicalCompletion,currentConsistency}}:{}});await h.ready();await h.click('recover');await h.click('statusCheck');assert.equal(h.state(),next);await h.locked();});
for(const [i,body]of [...badStatuses,null,[]].entries())test('post status unknown schema never reopens '+i,async()=>{const h=create({reply:({stage})=>stage==='STATUS_CHECKING'?{body}:{}});await h.ready();await h.click('recover');await h.click('statusCheck');assert(!['READY','PRECHECK'].includes(h.state()));await h.locked();});
test('double click while revalidation pending',async()=>{const h=create({reply:({stage})=>stage==='REVALIDATING'?{pending:true}:{}});await h.ready();const p=h.click('recover');await h.click('recover');await flush();assert.equal(h.calls.length,3);h.release();await flush();h.release();await p;assert.equal(h.writes().length,1);await h.locked();});
for(const reply of [{network:true},{nonJson:true},{version:'WRONG'},{body:{success:false,code:'UPSTREAM_TIMEOUT'}},{body:{...status,extra:'PRIVATE_RESPONSE'}}])test('post-attempt read failure stays locked '+JSON.stringify(reply),async()=>{const h=create({reply:({stage})=>stage==='STATUS_CHECKING'?reply:{}});await h.ready();await h.click('recover');await h.click('statusCheck');assert.equal(h.state(),'WRITE_RESULT_UNKNOWN');await h.locked();});
